[package]
name = "battleship_game_logic"
version = "0.1.0"
authors = ["Rainer <rainer@software-architects.at>"]
edition = "2018"

[dependencies]
rand = "^0.8.0"
getrandom = { version = "^0.2.0", features = [ "js" ] }

[dev-dependencies]
rstest = "^0.11.0"
mockall = "^0.10.0"
